db = db.getSiblingDB("test")
db.raw.drop()
db.raw.createIndex({timestamp: 1})
db.raw.createIndex({timestamp: -1})
db.raw.createIndex({did: 1})
db.raw.createIndex({product_key: 1})
db.raw.createIndex({type: 1})
db.raw.createIndex({ts: -1})
db.raw.createIndex({did: 1, type: 1, timestamp: 1})
db.raw.getIndexes()
db.raw.stats()
